apiVersion: v1
kind: Service
metadata:
  name: {{ include "ibgw.fullname" . }}
  labels:
    {{- include "ibgw.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 4001
      protocol: TCP
      name: ibgw
  selector:
    {{- include "ibgw.selectorLabels" . | nindent 4 }}
